### ISSUE TITLE
Live preview is not working

### ISSUE THREAD

**Issue by GalacticGazelle** [Dinujaya-Sandaruwan/Youtube-Data-From-API#1]
### Your live preview is not working. I think it is some API issues. Can you try to fix this.

![image](https://user-images.githubusercontent.com/127184010/225127254-4efce6cc-a27a-4f95-9204-7c5fc9824ab6.png)

**Comment by Dinujaya-Sandaruwan** [comment]
Yes, My API was not working and I fixed it. 😊😊
